# SQL Server

# default: &default
#   adapter: sqlserver
#   database: daotaodn
#   host: 222.255.132.62
#   username: cndata1
#   password: 123456
#
# development:
#   <<: *default
#   database: DaoTao_development
#
#
# test:
#   <<: *default
#   database: DaoTao_test
#
# production:
#   <<: *default
#   database: DaoTao_production
#   username: DaoTao
#   password: <%= ENV['DEMOTEST_DATABASE_PASSWORD'] %>





# MySQL. Versions 5.0 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: longlong
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: DaoTao_development




test:
  <<: *default
  database: DaoTao_test


production:
  <<: *default
  database: DaoTao_production
  username: DaoTao
  password: <%= ENV['DEMOTEST_DATABASE_PASSWORD'] %>
