# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 913132b17803312eac29dc2a90db4e4adfa5a860c543af07a140a6ba20a37641b207338af57bc35bb6a1e09d77892167c7108dcc4475b04bc927113cf6976347

test:
  secret_key_base: 71e465bc3f12f84eab48eebbf2095c6685f0423bede55d54f662d61dad3c96f17c9da9da09862d989124f8c9a8eea3cfc118a86d44ece1a76b7cc00a8fd96fd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
